dependencies:
  - anaconda::gcc
  - anaconda::docopt
  - anaconda::svn
  - anaconda::graphviz
  - r::r
  - conda-forge::jags
  - conda-forge::r-rtsne=0.13
  - bioconda::snakemake=4.3.0
  - bioconda::bioconductor-biocinstaller=1.28.0
  - bioconda::bioconductor-genomicfeatures=1.28.5
  - bioconda::bioconductor-variantannotation=1.22.3
  - bioconda::bioconductor-signer=1.2.2
  - bioconda::bioconductor-rbgl=1.54.0
  - bioconda::bioconductor-pcamethods=1.68.0
  - bioconda::vcftools
  - conda-forge::r-docopt=0.4.5
  - bioconda::bioconductor-bsgenome.hsapiens.ucsc.hg19=1.4.0
  - r::r-essentials
  - conda-forge::r-devtools=1.13.2
  - conda-forge::r-roxygen2=6.0.1
  - r::r-stringr
  - conda-forge::r-rcpp=0.12.10
  - conda-forge::r-readr=1.1.0
  - conda-forge::r-purrr=0.2.2
  - conda-forge::r-broom=0.4.2
  - conda-forge::r-tidyr=0.6.1
  - conda-forge::r-dplyr=0.7.0
  - conda-forge::r-ggplot2=2.2.0
  - r::r-tidyverse
  - r::r-doparallel
  - conda-forge::r-stanheaders=2.15.0
  - conda-forge::r-rstan=2.15.1
