channels:
  - bioconda
  - defaults
  - anaconda
dependencies:
  - gcc
  - docopt
  - r-essentials
  - r-devtools
  - r-roxygen2
  - r-docopt
  - r-stringr
  - r-tidyverse
  - r-doparallel
  - r-rtsne 
  - r-purrr
  - svn
  - lapack
  - snakemake
  - bioconductor-biocinstaller
  - bioconductor-variantannotation
