dependencies:
  - anaconda::gcc
  - anaconda::docopt
  - anaconda::svn
  - r::r
  - conda-forge::jags
  - conda-forge::r-rtsne=0.13
  - bioconda::snakemake=4.3.0
  - bioconda::bioconductor-biocinstaller=1.28.0
  - bioconda::bioconductor-genomicfeatures=1.28.5
  - bioconda::bioconductor-variantannotation=1.22.3
  - bioconda::bioconductor-signer=1.2.2
  - bioconda::bioconductor-rbgl=1.54.0
  - bioconda::bioconductor-pcamethods=1.68.0
  - bioconda::vcftools=0.1.15
  - bioconda::r-docopt=0.4.5
  - bioconda::r-matlab=1.0.2
  - bioconda::bioconductor-bsgenome.hsapiens.ucsc.hg19=1.4.0
  - r::r-essentials
  - r::r-devtools
  - r::r-roxygen2
  - r::r-stringr
  - r::r-tidyverse
  - r::r-doparallel
  - r::r-rstan
