name: dependencies
channels:
- bioconda
- conda-forge
- r
- defaults
dependencies:
- vcftools
- bioconductor-signer
- bioconductor-variantannotation
- snakemake
- r-docopt
- r-matlab
- r-rtsne
- docopt
- gcc
- glib
- gmp
- r-base
- r-essentials
- r-devtools
- r-doparallel
- r-tidyverse
- r-knitr
- r-plyr
- r-roxygen2
- r-stringr
