channels:
  - bioconda
  - r
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - gcc
  - docopt
  - r-essentials
  - r-devtools
  - r-docopt
  - r-stringr
  - r-tidyverse
  - r-doparallel
  - r-matlab
  - r-rstan
  - r-tsne 
  - r-purrr
  - lapack
  - snakemake
  - bioconductor-biocinstaller
  - bioconductor-variantannotation
  - bioconductor-signer
